
export const GET_COURSES_LOAD = "GET_COURSES_LOAD";
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_FAIL = "GET_ALL_LEVELS";

export const COURSE_DETAILS_LOAD = "COURSE_DETAILS_LOAD";
export const COURSE_DETAILS_SUCCESS = "COURSE_DETAILS_SUCCESS";
export const COURSE_DETAILS_FAIL = "COURSE_DETAILS_FAIL";

export const ADD_COURSE_LOAD = "ADD_COURSE_LOAD";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAIL = "ADD_COURSE_FAIL";

export const LOAD_EDITCOURSE = "LOAD_EDITCOURSE";
export const EDITCOURSE_SUCCESS = "EDITCOURSE_SUCCESS";
export const FAIL_EDITCOURSE = "FAIL_EDITCOURSE";




